using Microsoft.Bot.Schema;
using Newtonsoft.Json;

namespace SearchCommand
{
    public class AIEntity : Entity
    {
        /// <summary>
        /// Required. Must be "https://schema.org/Message"
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public new string Type = "https://schema.org/Message";

        /// <summary>
        /// Required. Must be "Message".
        /// </summary>
        [JsonProperty(PropertyName = "@type")]
        public string AtType = "Message";

        /// <summary>
        /// Required. Must be "https://schema.org"
        /// </summary>
        [JsonProperty(PropertyName = "@context")]
        public string AtContext = "https://schema.org";

        /// <summary>
        /// Must be left blank. This is for Bot Framework's schema.
        /// </summary>
        [JsonProperty(PropertyName = "@id")]
        public string AtId = "";

        /// <summary>
        /// Indicate that the content was generated by AI.
        /// </summary>
        [JsonProperty(PropertyName = "additionalType")]
        public List<string> AdditionalType = new() { "AIGeneratedContent" };
    }
}
